dependencies:
  config:
    - field.field.node.event.field_event_date_end
dependencies:
  module:
    - address
    - datetime
content:
  field_event_date:
    type: datetime_default
    weight: 2
    region: content
    label: hidden
    settings:
      format_type: medium
      timezone_override: ''
    third_party_settings: {  }
  field_event_location:
    type: address_default
    weight: 3
    region: content
    label: hidden
    settings: {  }
    third_party_settings: {  }
  field_event_date_end:
    type: datetime_default
    weight: 4
    region: content
    label: hidden
    settings:
      format_type: medium
      timezone_override: ''
    third_party_settings: {  }