custom:
  -
    path: /
    priority: !!float 1
entity_types:
  node: {  }
  taxonomy_term: {  }
  menu_link_content: {  }
settings:
  max_links: 2000
  cron_generate: true
  remove_duplicates: true
  skip_untranslated: false
  batch_process_limit: 1500
_core:
  default_config_hash: Gzm-Hm6hFi622JTbULwDXMxPi33rj_mF0pi1ggq6sFQ
langcode: de
