display:
  default:
    display_options:
      pager:
        type: full
        options:
          items_per_page: 12
          offset: 0
          id: 0
          total_pages: null
          tags:
            previous: ‹‹
            next: ››
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page: false
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options: '5, 10, 25, 50'
            items_per_page_options_all: false
            items_per_page_options_all_label: '- Alle -'
            offset: false
            offset_label: Offset
          quantity: 9
      row:
        options:
          view_modes:
            'entity:media':
              address: search
              audio: search
              citation: search
              contact: search
              document: search
              gallery: search
              image: search
              instagram: search
              person: search
              tweet: search
              video: search
              video_upload: search