third_party_settings:
  field_group:
    group_media:
      children:
        - field_media_video_embed_field
        - field_video_preview
content:
  field_video_preview:
    type: entity_browser_entity_reference
    weight: 4
    settings:
      entity_browser: media_browser
      field_widget_display: rendered_entity
      field_widget_edit: true
      field_widget_remove: true
      selection_mode: selection_append
      field_widget_display_settings:
        view_mode: thumbnail
      open: true
    region: content
    third_party_settings: {  }