dependencies:
  config:
    - field.field.media.address.field_title
content:
  field_title:
    weight: 0
    label: hidden
    settings:
      link_to_entity: false
    third_party_settings: {  }
    type: string
    region: content
