dependencies:
  config:
    - field.field.media.image.field_allow_download
third_party_settings:
  field_group:
    group_media:
      children:
        - field_allow_download
content:
  field_allow_download:
    weight: 2
    settings:
      display_label: true
    third_party_settings: {  }
    type: boolean_checkbox
    region: content
