dependencies:
  config:
    - field.field.node.event.field_event_display_time
third_party_settings:
  field_group:
    group_date_and_time:
      children:
        - field_event_date
        - field_event_date_end
        - field_event_display_time
      parent_name: ''
      weight: 2
      format_type: fieldset
      format_settings:
        label: 'Datum und Uhrzeit'
        description: ''
        required_fields: true
        id: ''
        classes: ''
      label: 'Datum und Uhrzeit'
      region: content
content:
  created:
    weight: 8
  field_content_paragraphs:
    weight: 14
  field_event_date:
    weight: 3
  field_event_date_end:
    weight: 4
  field_event_display_time:
    weight: 5
    settings:
      display_label: true
    third_party_settings: {  }
    type: boolean_checkbox
    region: content
  field_event_location:
    weight: 1