dependencies:
  config:
    - field.field.media.document.field_title
content:
  field_title:
    weight: 1
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
    type: string_textfield
    region: content
