name: 'deGov - Social Media Settings'
description: 'Mit diesem Modul können Besucher steuern, welche Social Media Inhalte ihnen angezeigt werden.'
package: deGov
type: module
core: 8.x
dependencies:
  - config_rewrite
  - degov_eu_cookie_compliance

libraries:
  - degov_social_media_settings/process
