content:
  field_video_upload_preview:
    type: entity_reference_entity_view
    weight: 5
    region: content
    label: hidden
    settings:
      view_mode: teaser_squared_1_1
      link: false
    third_party_settings: {  }